// Expanded Magahit Author Marketing services.
// Existing services are preserved (wording kept); missing master-list services are added.
// Review / outreach services use ethical language only — no bought reviews, no rating manipulation.

export type Service = {
  slug: string;
  name: string;
  summary: string; // card description
  categoryId: string;
  problem: string;
  whatWeDo: string;
  process: string[];
  deliverables: string[];
  bestFor: string;
  benefits: string[];
  related: string[]; // slugs
};

export type ServiceCategory = {
  id: string;
  number: string;
  label: string; // full category name
  shortLabel: string; // filter chip label
  headline: string; // serif headline
  intro: string; // strategic explanation
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "discovery",
    number: "01",
    label: "Book Discovery & Review Visibility",
    shortLabel: "Discovery",
    headline: "Be Found by the Readers Already Looking for You",
    intro:
      "Discovery is the work of making sure the readers most likely to love your book can actually find it — through search, shelves, lists, and honest reader conversations.",
  },
  {
    id: "amazon",
    number: "02",
    label: "Amazon Optimization",
    shortLabel: "Amazon",
    headline: "Make It Easier for the Right Reader to Find Your Book",
    intro:
      "Your Amazon detail page is where most buying decisions happen. Small, deliberate improvements to keywords, categories, metadata, copy, and content compound across every visitor you earn.",
  },
  {
    id: "advertising",
    number: "03",
    label: "Paid Advertising",
    shortLabel: "Advertising",
    headline: "Disciplined Spend, Measured Against Real Outcomes",
    intro:
      "Advertising only works once the listing converts. We structure Amazon and Meta campaigns around reader intent, with budgets, testing plans, and reporting you can actually evaluate.",
  },
  {
    id: "content",
    number: "04",
    label: "Social Media & Content",
    shortLabel: "Content",
    headline: "A Presence That Says the Same Thing to the Same Reader",
    intro:
      "Content and social platforms are where an author's voice becomes recognisable. We build platform-specific plans you can sustain between books — not daily burnout.",
  },
  {
    id: "author-brand",
    number: "05",
    label: "Author Brand & Email Audience",
    shortLabel: "Author Brand",
    headline: "An Audience You Own, Not One You Rent",
    intro:
      "A career is built on an audience you can reach again for the next release. We define the author brand and build the email infrastructure that turns readers into a durable asset.",
  },
  {
    id: "media",
    number: "06",
    label: "Media & Podcast Outreach",
    shortLabel: "Outreach",
    headline: "Reach the Shows and Channels Your Readers Trust",
    intro:
      "The right interview, feature, or channel partnership places your book in front of engaged audiences who already trust the host. We pitch with relevance, not volume.",
  },
  {
    id: "institutional",
    number: "07",
    label: "Bookstores, Libraries & Institutional Sales",
    shortLabel: "Outreach",
    headline: "Beyond the Algorithm — Real Readers, Real Shelves",
    intro:
      "Some books find their audience through bookstores, libraries, book clubs, and institutions rather than ads. We handle the outreach that platforms cannot do for you.",
  },
  {
    id: "launch",
    number: "08",
    label: "Pre-Launch & Book Launch",
    shortLabel: "Launch",
    headline: "Build Momentum Before Launch Day, Not After It",
    intro:
      "Launch week amplifies whatever you built beforehand. We sequence the pre-launch, advance-reader, pre-order, and launch-week work so release day is execution, not improvisation.",
  },
  {
    id: "strategy",
    number: "09",
    label: "Marketing Strategy & Campaign Management",
    shortLabel: "Strategy",
    headline: "A Strategy, Not a List of Promotional Tasks",
    intro:
      "Before any tactic, there is a plan. We audit what your book needs, review what has already been tried, and run a defined campaign with clear success measures.",
  },
];

// Filter chips (master list's 8 browse paths). Media + Institutional share "Outreach".
export const SERVICE_FILTERS: { id: string; label: string; categories: string[] }[] = [
  { id: "discovery", label: "Discovery", categories: ["discovery"] },
  { id: "amazon", label: "Amazon", categories: ["amazon"] },
  { id: "advertising", label: "Advertising", categories: ["advertising"] },
  { id: "content", label: "Content", categories: ["content"] },
  { id: "author-brand", label: "Author Brand", categories: ["author-brand"] },
  { id: "outreach", label: "Outreach", categories: ["media", "institutional"] },
  { id: "launch", label: "Launch", categories: ["launch"] },
  { id: "strategy", label: "Strategy", categories: ["strategy"] },
];

export const SERVICES: Service[] = [
  // ============ 01 — Book Discovery & Review Visibility ============
  {
    slug: "goodreads-review-campaign",
    name: "Goodreads Review Campaign",
    categoryId: "discovery",
    summary:
      "A targeted reader outreach campaign designed to introduce your book to relevant readers and encourage honest, independent reviews from people who genuinely choose to read it.",
    problem:
      "Books need reader feedback to build credibility, but reviews cannot be bought or faked without risking your reputation and the platform's rules.",
    whatWeDo:
      "We design a respectful outreach campaign that connects your book with readers whose reading taste matches it, and invite genuine, voluntary feedback.",
    process: [
      "Define the reader profile from genre and comparable titles",
      "Build a targeted reader list based on reading behaviour",
      "Send honest, non-incentivised outreach with a copy for review",
      "Track engagement and report what was sent and what followed",
    ],
    deliverables: [
      "Reader targeting plan",
      "Outreach copy and sending schedule",
      "Engagement and response report",
    ],
    bestFor:
      "Authors whose book is ready for readers but lacks early social proof on Goodreads.",
    benefits: [
      "Builds credible, organic reader feedback",
      "Respects Goodreads review policies",
      "Creates a foundation of honest visibility",
    ],
    related: ["goodreads-reader-outreach", "goodreads-listopia-strategy", "book-reviewer-outreach", "arc-strategy"],
  },
  {
    slug: "amazon-review-campaign",
    name: "Amazon Review Campaign",
    categoryId: "discovery",
    summary:
      "Reader outreach designed to increase opportunities for genuine reader feedback and honest reviews while respecting Amazon's review policies.",
    problem:
      "Amazon reviews are one of the strongest buying signals, but incentivised or manipulated reviews violate policy and can damage your listing.",
    whatWeDo:
      "We run ethical reader outreach that introduces your book to the right readers and encourages honest, policy-compliant feedback on Amazon.",
    process: [
      "Map the ideal Amazon reader from comparable titles",
      "Build an outreach list aligned with reading taste",
      "Share the book with honest, non-incentivised language",
      "Report outreach activity and honest responses",
    ],
    deliverables: [
      "Targeted reader list",
      "Compliant outreach messaging",
      "Activity and response summary",
    ],
    bestFor:
      "Authors with a converting listing who need more genuine reader feedback.",
    benefits: [
      "Increases honest review opportunities",
      "Stays fully within Amazon's policies",
      "Supports long-term listing credibility",
    ],
    related: ["goodreads-review-campaign", "book-reviewer-outreach", "amazon-book-description-optimization", "social-proof-strategy"],
  },
  {
    slug: "goodreads-listopia-strategy",
    name: "Goodreads Listopia Strategy",
    categoryId: "discovery",
    summary: "Position your title alongside comparable books readers already trust.",
    problem:
      "Readers browse Goodreads lists to find their next book. If your title is not positioned next to comparable reads, it is invisible to that discovery path.",
    whatWeDo:
      "We identify the most relevant Listopia lists for your genre and position your book alongside the comparable titles your readers already love.",
    process: [
      "Identify comparable titles and their list placements",
      "Select relevant, active Listopia lists",
      "Position your book within the right lists",
      "Monitor list visibility over time",
    ],
    deliverables: [
      "Comparable-title and list research",
      "List placement plan",
      "Visibility tracking notes",
    ],
    bestFor: "Authors whose readers discover books through Goodreads lists and shelves.",
    benefits: ["Places your book where readers browse", "Builds association with trusted titles", "Low-cost visibility"],
    related: ["goodreads-reader-outreach", "goodreads-review-campaign", "book-marketing"],
  },
  {
    slug: "goodreads-reader-outreach",
    name: "Goodreads Reader Outreach",
    categoryId: "discovery",
    summary:
      "Targeted outreach to relevant Goodreads readers based on genre, comparable titles, interests, and reading behaviour.",
    problem:
      "Goodreads is where serious readers decide, but reaching the right ones requires research, not mass messaging.",
    whatWeDo:
      "We research reader behaviour on Goodreads — shelves, lists, and ratings of comparable titles — and reach out to the readers most likely to genuinely enjoy your book.",
    process: [
      "Analyse comparable-title shelving and rating behaviour",
      "Build a targeted reader outreach list",
      "Send honest, personalised outreach",
      "Report engagement and responses",
    ],
    deliverables: ["Reader behaviour research", "Targeted outreach list", "Outreach copy and report"],
    bestFor: "Authors who want honest Goodreads visibility from real readers.",
    benefits: ["Reaches readers by behaviour, not guesswork", "Builds real Goodreads presence", "Supports honest reviews"],
    related: ["goodreads-review-campaign", "goodreads-listopia-strategy", "goodreads-marketing"],
  },
  {
    slug: "book-reviewer-outreach",
    name: "Book Reviewer Outreach",
    categoryId: "discovery",
    summary: "Personalised outreach to established reviewers who cover your genre.",
    problem:
      "Reviewers receive hundreds of pitches. Generic outreach gets ignored; the right pitch to the right reviewer gets read.",
    whatWeDo:
      "We research reviewers who actively cover your genre and pitch your book with a personalised, relevant approach.",
    process: [
      "Research active reviewers in your genre",
      "Qualify each reviewer's taste and submission rules",
      "Write a personalised pitch and follow-up",
      "Track responses and coverage",
    ],
    deliverables: ["Qualified reviewer list", "Personalised pitch copy", "Response and coverage tracker"],
    bestFor: "Authors who want considered, honest coverage from genre-matched reviewers.",
    benefits: ["Reaches reviewers likely to engage", "Builds genuine coverage", "Improves with each cycle"],
    related: ["book-blogger-outreach", "romance-reviewer-outreach", "non-fiction-reviewer-outreach", "arc-strategy"],
  },
  {
    slug: "book-blogger-outreach",
    name: "Book Blogger Outreach",
    categoryId: "discovery",
    summary: "Personalised outreach to reviewers and bloggers who cover your genre.",
    problem:
      "Book bloggers still influence dedicated reader communities, but only respond to relevant, respectful pitches.",
    whatWeDo:
      "We identify bloggers whose audience overlaps with your ideal reader and pitch your book with genuine, tailored messaging.",
    process: ["Research active genre bloggers", "Match taste and submission policy", "Send tailored pitches", "Track features and coverage"],
    deliverables: ["Curated blogger list", "Tailored pitch copy", "Coverage report"],
    bestFor: "Authors whose readers follow book blogs and review sites.",
    benefits: ["Builds authentic blog coverage", "Reaches engaged reader communities", "Creates shareable content"],
    related: ["book-reviewer-outreach", "bookstagram-outreach", "podcast-outreach"],
  },
  {
    slug: "reader-outreach",
    name: "Reader Outreach",
    categoryId: "discovery",
    summary: "Targeted introductions to reader communities aligned with your story.",
    problem:
      "Your ideal readers already gather in communities — forums, groups, shelves — but reaching them without spamming takes care.",
    whatWeDo:
      "We identify reader communities aligned with your genre and introduce your book honestly and respectfully.",
    process: ["Map relevant reader communities", "Understand community norms", "Craft honest introductions", "Track engagement"],
    deliverables: ["Community research", "Introduction messaging", "Engagement summary"],
    bestFor: "Authors whose readers gather in genre communities and groups.",
    benefits: ["Reaches concentrated reader audiences", "Builds word-of-mouth", "Respects community norms"],
    related: ["goodreads-reader-outreach", "book-club-outreach", "bookstagram-outreach"],
  },
  {
    slug: "romance-reviewer-outreach",
    name: "Romance Reviewer Outreach",
    categoryId: "discovery",
    summary: "Outreach to reviewers and bloggers who specialise in romance and its subgenres.",
    problem:
      "Romance readers are loyal and specific — tropes and subgenres matter. Generic outreach misses the reviewers they trust.",
    whatWeDo:
      "We target romance reviewers by trope, heat level, and subgenre so your pitch lands with readers who actually want it.",
    process: ["Define your trope and subgenre fit", "Research trope-matched reviewers", "Send tailored pitches", "Track responses"],
    deliverables: ["Trope and subgenre map", "Reviewer match list", "Pitch copy and tracker"],
    bestFor: "Romance authors whose readers follow specific tropes and reviewers.",
    benefits: ["Reaches trope-aware reviewers", "Higher response rates", "Builds subgenre credibility"],
    related: ["book-reviewer-outreach", "book-blogger-outreach", "bookstagram-outreach"],
  },
  {
    slug: "non-fiction-reviewer-outreach",
    name: "Non-Fiction Reviewer Outreach",
    categoryId: "discovery",
    summary: "Outreach to reviewers, bloggers, and subject communities focused on non-fiction.",
    problem:
      "Non-fiction readers evaluate by authority, topic, and applicability — different reviewers than fiction.",
    whatWeDo:
      "We research non-fiction reviewers and subject-matter communities aligned with your topic and pitch for honest, informed coverage.",
    process: ["Define topic and authority angle", "Research topic-focused reviewers", "Pitch with relevant authority", "Track coverage"],
    deliverables: ["Topic and authority brief", "Reviewer and community list", "Pitch copy and tracker"],
    bestFor: "Non-fiction authors building authority and topic credibility.",
    benefits: ["Reaches informed reviewers", "Builds topic authority", "Supports long-tail discovery"],
    related: ["book-reviewer-outreach", "philosophy-blogger-outreach", "psychology-blogger-outreach", "podcast-outreach"],
  },
  {
    slug: "philosophy-blogger-outreach",
    name: "Philosophy Blogger Outreach",
    categoryId: "discovery",
    summary: "Outreach to bloggers and communities engaged with philosophy and ideas.",
    problem:
      "Philosophy readers are discerning and community-driven; they respond to substance, not promotion.",
    whatWeDo:
      "We identify philosophy-focused bloggers and communities and pitch your work with genuine intellectual relevance.",
    process: ["Map philosophy blogs and communities", "Qualify relevance and audience", "Craft substantive pitches", "Track engagement"],
    deliverables: ["Philosophy blog and community list", "Substantive pitch copy", "Engagement report"],
    bestFor: "Philosophy authors and idea-driven non-fiction writers.",
    benefits: ["Reaches engaged idea communities", "Builds intellectual credibility", "Creates considered coverage"],
    related: ["non-fiction-reviewer-outreach", "psychology-blogger-outreach", "podcast-outreach", "university-department-outreach"],
  },
  {
    slug: "psychology-blogger-outreach",
    name: "Psychology Blogger Outreach",
    categoryId: "discovery",
    summary: "Outreach to bloggers and communities focused on psychology and behaviour.",
    problem:
      "Psychology readers look for evidence and clarity; promotion that oversells undermines credibility.",
    whatWeDo:
      "We reach psychology-focused bloggers and communities with honest, relevant pitches that respect the audience's standards.",
    process: ["Map psychology blogs and communities", "Qualify audience and standards", "Send honest, relevant pitches", "Track coverage"],
    deliverables: ["Psychology blog list", "Relevant pitch copy", "Coverage report"],
    bestFor: "Psychology and self-development non-fiction authors.",
    benefits: ["Reaches evidence-minded readers", "Builds topic authority", "Encourages honest coverage"],
    related: ["non-fiction-reviewer-outreach", "philosophy-blogger-outreach", "podcast-outreach"],
  },
  {
    slug: "arc-strategy",
    name: "Advance Review (ARC) Strategy",
    categoryId: "discovery",
    summary:
      "Structured advance-reader outreach designed to generate legitimate early readership and encourage honest feedback before and around launch.",
    problem:
      "Launches need early readers and reviews, but rushed or incentivised ARCs break platform rules and trust.",
    whatWeDo:
      "We build an ethical advance-reader programme that recruits genuine readers and encourages honest, timely feedback around launch.",
    process: ["Recruit matched advance readers", "Set honest expectations", "Distribute and follow up", "Track honest feedback"],
    deliverables: ["ARC reader recruitment plan", "Distribution and follow-up schedule", "Feedback summary"],
    bestFor: "Authors preparing a launch who need legitimate early readership.",
    benefits: ["Builds honest early reviews", "Supports launch-week momentum", "Stays policy-compliant"],
    related: ["pre-launch-campaigns", "goodreads-review-campaign", "amazon-review-campaign", "launch-week-strategy"],
  },

  // ============ 02 — Amazon Optimization ============
  {
    slug: "amazon-keyword-optimization",
    name: "Amazon Keyword Optimization",
    categoryId: "amazon",
    summary: "Research the search terms real readers use in your genre and map them to your metadata.",
    problem: "Most books target keywords no reader actually searches, or keywords too competitive to rank for.",
    whatWeDo: "We research the real search terms readers use in your genre and map them to your backend keywords and listing.",
    process: ["Research reader search behaviour", "Map relevant, attainable keywords", "Apply to backend fields", "Refine against performance"],
    deliverables: ["Keyword research report", "Backend keyword mapping", "Application guidance"],
    bestFor: "Authors whose book is hard to find through Amazon search.",
    benefits: ["Improves search relevance", "Targets attainable terms", "Compounds with other metadata work"],
    related: ["amazon-category-research", "backend-metadata-optimization", "amazon-book-description-optimization"],
  },
  {
    slug: "amazon-category-research",
    name: "Amazon Category Research",
    categoryId: "amazon",
    summary: "Identify relevant, competitive categories where your book has a genuine chance of visibility.",
    problem: "Categories chosen by ambition rather than fit leave your book buried beneath bestsellers.",
    whatWeDo: "We identify categories where your book genuinely fits and has a real chance of visibility.",
    process: ["Analyse comparable titles' categories", "Assess competitiveness and fit", "Select primary and secondary categories", "Apply and refine"],
    deliverables: ["Category fit analysis", "Category placement plan", "Application guidance"],
    bestFor: "Authors whose book is miscategorised or lost in overly broad categories.",
    benefits: ["Improves browse visibility", "Targets attainable rankings", "Aligns with reader browsing"],
    related: ["amazon-keyword-optimization", "backend-metadata-optimization", "a-plus-content"],
  },
  {
    slug: "backend-metadata-optimization",
    name: "Backend Metadata Optimization",
    categoryId: "amazon",
    summary: "Align title, subtitle, series data, and back-end fields into one coherent listing.",
    problem: "Inconsistent backend metadata sends mixed relevance signals and weakens discoverability.",
    whatWeDo: "We align your title, subtitle, series, contributors, and back-end fields into a single coherent, discoverable listing.",
    process: ["Audit current metadata", "Align fields with reader intent", "Apply consistent data", "Review against comparable titles"],
    deliverables: ["Metadata audit", "Aligned field mapping", "Application guidance"],
    bestFor: "Authors with incomplete or inconsistent listing metadata.",
    benefits: ["Strengthens relevance signals", "Improves discovery across paths", "Reduces listing confusion"],
    related: ["amazon-keyword-optimization", "amazon-category-research", "amazon-book-description-optimization"],
  },
  {
    slug: "amazon-book-description-optimization",
    name: "Amazon Book Description Optimization",
    categoryId: "amazon",
    summary: "Rewrite your description as persuasive, genre-aware sales copy.",
    problem: "Descriptions written like synopses don't sell; they summarise the plot instead of the experience.",
    whatWeDo: "We rewrite your description as persuasive, genre-aware sales copy that converts interested readers into buyers.",
    process: ["Analyse reader intent and genre hooks", "Draft and refine sales copy", "Format for readability", "Test against comparable titles"],
    deliverables: ["Rewritten description", "Formatting guide", "Variants for testing"],
    bestFor: "Authors whose listing gets traffic but few sales.",
    benefits: ["Improves conversion", "Speaks to genre expectations", "Supports ad performance"],
    related: ["a-plus-content", "backend-metadata-optimization", "social-proof-strategy"],
  },
  {
    slug: "a-plus-content",
    name: "A+ Content Creation",
    categoryId: "amazon",
    summary: "Design visual modules that support the buying decision on your detail page.",
    problem: "Text-only listings miss the chance to reassure and persuade readers at the point of decision.",
    whatWeDo: "We plan and design A+ Content modules that support the buying decision and reinforce your book's positioning.",
    process: ["Define decision-stage objections", "Plan module structure", "Design visual content", "Apply and refine"],
    deliverables: ["A+ Content module plan", "Visual design direction", "Application guidance"],
    bestFor: "Authors with a converting description who want to lift conversion further.",
    benefits: ["Reinforces buying decision", "Differentiates the listing", "Improves conversion"],
    related: ["amazon-book-description-optimization", "backend-metadata-optimization", "sales-page-optimization"],
  },
  {
    slug: "sales-page-optimization",
    name: "Sales Page Optimization",
    categoryId: "amazon",
    summary: "Improve your own site's book page so traffic you earn actually converts.",
    problem: "Traffic driven to your own book page often lands on a page that doesn't convert.",
    whatWeDo: "We improve your own site's book page so the traffic you earn from outreach and content actually converts.",
    process: ["Audit the current book page", "Improve copy and structure", "Strengthen social proof and CTA", "Refine over time"],
    deliverables: ["Page audit", "Copy and layout recommendations", "Conversion guidance"],
    bestFor: "Authors driving traffic to their own site rather than a retailer.",
    benefits: ["Converts earned traffic", "Reinforces brand", "Supports direct sales"],
    related: ["amazon-book-description-optimization", "a-plus-content", "author-brand-development"],
  },
  {
    slug: "social-proof-strategy",
    name: "Social Proof Strategy",
    categoryId: "amazon",
    summary: "Present genuine reviews, endorsements, and reader reactions where they matter most.",
    problem: "Even great reviews fail to help if they're buried or poorly presented.",
    whatWeDo: "We surface genuine reviews, endorsements, and reader reactions in the places that influence the buying decision.",
    process: ["Audit existing social proof", "Map decision-stage touchpoints", "Position authentic proof", "Refine presentation"],
    deliverables: ["Social proof audit", "Placement plan", "Presentation guidance"],
    bestFor: "Authors with reviews and endorsements that aren't working hard enough.",
    benefits: ["Builds trust at decision point", "Uses only authentic proof", "Improves conversion"],
    related: ["amazon-review-campaign", "amazon-book-description-optimization", "a-plus-content"],
  },

  // ============ 03 — Paid Advertising ============
  {
    slug: "amazon-ads",
    name: "Amazon Ads",
    categoryId: "advertising",
    summary: "Keyword, product, and category targeting structured for your genre.",
    problem: "Amazon Ads waste budget fast when targeting, copy, and bids aren't structured around reader intent.",
    whatWeDo: "We structure Amazon Ads campaigns — keyword, product, and category targeting — around how readers in your genre actually search.",
    process: ["Research targets and intent", "Structure campaigns and ad groups", "Write ad copy", "Launch, monitor, optimise"],
    deliverables: ["Campaign structure", "Target and keyword plan", "Ad copy and reporting"],
    bestFor: "Authors with a converting listing ready to scale visibility.",
    benefits: ["Targets reader intent", "Measurable spend", "Scales what already works"],
    related: ["long-tail-keyword-advertising", "campaign-strategy", "campaign-management", "optimization"],
  },
  {
    slug: "meta-ads",
    name: "Meta Ads (Facebook & Instagram)",
    categoryId: "advertising",
    summary: "Audience testing and creative built for reader intent, not vanity clicks.",
    problem: "Meta campaigns often chase clicks from people who never read, burning budget on the wrong audience.",
    whatWeDo: "We build Meta campaigns with audience testing and creative aimed at genuine reader intent, not vanity engagement.",
    process: ["Define reader audiences", "Test creative and angles", "Allocate budget by performance", "Optimise and scale"],
    deliverables: ["Audience and creative plan", "Campaign build", "Performance reporting"],
    bestFor: "Authors who want to reach readers off-Amazon with measurable spend.",
    benefits: ["Reaches readers off-platform", "Tests audience hypotheses", "Built around reader intent"],
    related: ["amazon-ads", "campaign-strategy", "campaign-management", "instagram-book-promotion"],
  },
  {
    slug: "long-tail-keyword-advertising",
    name: "Long-Tail Keyword Advertising",
    categoryId: "advertising",
    summary: "Target specific, low-competition search terms where your book can genuinely rank.",
    problem: "Competing for broad keywords is expensive and rarely wins; the affordable wins are in long-tail terms.",
    whatWeDo: "We identify and target specific, low-competition long-tail keywords where your book can genuinely appear and convert.",
    process: ["Mine long-tail search terms", "Assess competition and intent", "Build targeted campaigns", "Refine by performance"],
    deliverables: ["Long-tail keyword research", "Campaign structure", "Performance reporting"],
    bestFor: "Authors with limited ad budgets who need affordable visibility.",
    benefits: ["Lower cost per click", "Higher intent matching", "Realistic ranking chances"],
    related: ["amazon-ads", "amazon-keyword-optimization", "optimization"],
  },
  {
    slug: "campaign-strategy",
    name: "Campaign Strategy",
    categoryId: "advertising",
    summary: "Budget structure, testing plan, and success criteria agreed in advance.",
    problem: "Ad campaigns fail when budget, testing, and success measures aren't defined before launch.",
    whatWeDo: "We define the budget structure, testing plan, and success criteria for your campaign before any spend.",
    process: ["Define goals and constraints", "Structure budget and tests", "Agree success criteria", "Document the plan"],
    deliverables: ["Campaign strategy document", "Budget and testing plan", "Success measures"],
    bestFor: "Authors about to invest in paid promotion.",
    benefits: ["Clear success measures", "Disciplined spend", "Reduces wasted budget"],
    related: ["amazon-ads", "meta-ads", "campaign-management", "optimization"],
  },
  {
    slug: "campaign-management",
    name: "Campaign Management",
    categoryId: "advertising",
    summary: "Ongoing monitoring, bid management, and reporting.",
    problem: "Campaigns drift without active management — bids creep, targets fatigue, performance quietly declines.",
    whatWeDo: "We provide ongoing monitoring, bid management, and transparent reporting across your campaigns.",
    process: ["Monitor performance daily", "Manage bids and budgets", "Refresh fatigued targets", "Report clearly"],
    deliverables: ["Ongoing management", "Bid and budget adjustments", "Regular reporting"],
    bestFor: "Authors running active campaigns who need hands-on management.",
    benefits: ["Keeps performance stable", "Catches issues early", "Transparent reporting"],
    related: ["campaign-strategy", "optimization", "amazon-ads", "meta-ads"],
  },
  {
    slug: "optimization",
    name: "Optimization",
    categoryId: "advertising",
    summary: "Regular pruning, scaling, and creative iteration based on data.",
    problem: "Even managed campaigns stagnate without systematic pruning, scaling, and creative iteration.",
    whatWeDo: "We run regular optimisation cycles — pruning what fails, scaling what works, and iterating creative based on data.",
    process: ["Review performance data", "Prune underperformers", "Scale winners", "Iterate creative"],
    deliverables: ["Optimisation cycle reports", "Pruning and scaling actions", "Creative iterations"],
    bestFor: "Authors with active campaigns seeking better return over time.",
    benefits: ["Improves return on spend", "Reduces wasted budget", "Keeps creative fresh"],
    related: ["campaign-management", "campaign-strategy", "amazon-ads"],
  },

  // ============ 04 — Social Media & Content ============
  {
    slug: "social-media-strategy",
    name: "Social Media Strategy",
    categoryId: "content",
    summary: "A realistic platform plan built around the readers you actually want.",
    problem: "Authors spread across every platform and burn out without reaching their actual readers.",
    whatWeDo: "We build a realistic platform plan focused on the channels where your readers actually are.",
    process: ["Identify reader platforms", "Define platform role", "Set a sustainable cadence", "Plan content themes"],
    deliverables: ["Platform strategy", "Cadence and theme plan", "Channel priorities"],
    bestFor: "Authors unsure which platforms deserve their time.",
    benefits: ["Focuses effort", "Sustainable cadence", "Reaches the right readers"],
    related: ["content-strategy", "content-pillars", "content-repurposing"],
  },
  {
    slug: "content-strategy",
    name: "Content Strategy",
    categoryId: "content",
    summary: "Content pillars and formats you can sustain between books.",
    problem: "Random content doesn't build an author; consistent themes do.",
    whatWeDo: "We define content pillars and formats you can sustain between releases to build a recognisable presence.",
    process: ["Define pillars from your author brand", "Choose sustainable formats", "Plan a content calendar", "Refine over time"],
    deliverables: ["Content pillar plan", "Format guide", "Calendar framework"],
    bestFor: "Authors who need a repeatable content system.",
    benefits: ["Builds recognition", "Sustainable output", "Supports each release"],
    related: ["social-media-strategy", "content-pillars", "content-repurposing", "book-quotes-content"],
  },
  {
    slug: "instagram-book-promotion",
    name: "Instagram Book Promotion",
    categoryId: "content",
    summary: "Visual content and community engagement built for Instagram's reader culture.",
    problem: "Instagram rewards aesthetic consistency and community, not random book plugs.",
    whatWeDo: "We build an Instagram presence around visual consistency and genuine reader-community engagement.",
    process: ["Define visual identity", "Plan content formats", "Engage reader communities", "Refine with data"],
    deliverables: ["Visual identity guide", "Content plan", "Engagement approach"],
    bestFor: "Authors whose readers discover books visually on Instagram.",
    benefits: ["Builds visual recognition", "Engages reader communities", "Supports launches"],
    related: ["tiktok-book-promotion", "book-imagery-content", "bookstagram-outreach", "content-repurposing"],
  },
  {
    slug: "facebook-book-promotion",
    name: "Facebook Book Promotion",
    categoryId: "content",
    summary: "Organic presence and reader-group engagement on Facebook.",
    problem: "Facebook's reader groups and pages still drive discovery, but only with genuine participation.",
    whatWeDo: "We build an organic Facebook presence and engage reader groups where your readers gather.",
    process: ["Identify relevant reader groups", "Plan organic content", "Engage genuinely", "Track engagement"],
    deliverables: ["Group and page plan", "Organic content approach", "Engagement notes"],
    bestFor: "Authors whose readers are active in Facebook reading groups.",
    benefits: ["Reaches established reader groups", "Builds word-of-mouth", "Supports launches"],
    related: ["meta-ads", "social-media-strategy", "content-repurposing"],
  },
  {
    slug: "tiktok-book-promotion",
    name: "TikTok Book Promotion",
    categoryId: "content",
    summary: "Short-form video content built for BookTok's reader-driven discovery.",
    problem: "BookTok can move books, but performative or off-trend content gets ignored.",
    whatWeDo: "We create authentic short-form video content that fits BookTok's reader-driven culture and trends.",
    process: ["Research genre trends and sounds", "Plan authentic formats", "Produce short-form video", "Engage and iterate"],
    deliverables: ["Trend and format research", "Content plan", "Production guidance"],
    bestFor: "Authors whose genre has an active BookTok community.",
    benefits: ["Taps reader-driven discovery", "Authentic to the platform", "High reach potential"],
    related: ["instagram-book-promotion", "book-quotes-content", "content-repurposing", "reader-engagement-content"],
  },
  {
    slug: "twitter-x-book-promotion",
    name: "Twitter/X Book Promotion",
    categoryId: "content",
    summary: "Author voice and community engagement on X.",
    problem: "X rewards consistent author voice and community participation, not broadcast promotion.",
    whatWeDo: "We build an X presence around your author voice and genuine engagement with reader and writer communities.",
    process: ["Define author voice", "Plan content themes", "Engage writing communities", "Refine over time"],
    deliverables: ["Voice and theme guide", "Content plan", "Engagement approach"],
    bestFor: "Authors who can sustain a conversational, voice-led presence.",
    benefits: ["Builds author voice", "Engages writing communities", "Supports networking"],
    related: ["threads-book-promotion", "social-media-strategy", "content-repurposing"],
  },
  {
    slug: "linkedin-book-promotion",
    name: "LinkedIn Book Promotion",
    categoryId: "content",
    summary: "Authority-led content for non-fiction and professional authors.",
    problem: "Non-fiction authors often overlook LinkedIn, where their professional readers actually are.",
    whatWeDo: "We build an authority-led LinkedIn presence that reaches professional readers and decision-makers.",
    process: ["Define authority angle", "Plan thought-leadership content", "Engage relevant audiences", "Refine"],
    deliverables: ["Authority angle", "Content plan", "Audience targeting"],
    bestFor: "Non-fiction and business authors reaching professional readers.",
    benefits: ["Builds professional authority", "Reaches decision-makers", "Supports institutional sales"],
    related: ["non-fiction-reviewer-outreach", "university-department-outreach", "institutional-book-sales"],
  },
  {
    slug: "threads-book-promotion",
    name: "Threads Book Promotion",
    categoryId: "content",
    summary: "Conversational, text-led content for the Threads reader community.",
    problem: "Threads rewards genuine conversation; broadcast posts get buried.",
    whatWeDo: "We build a conversational, text-led Threads presence that fits how readers actually engage there.",
    process: ["Define conversational voice", "Plan discussion-led content", "Engage authentically", "Refine"],
    deliverables: ["Voice guide", "Content plan", "Engagement approach"],
    bestFor: "Authors whose readers prefer text-led, conversational platforms.",
    benefits: ["Builds authentic conversation", "Reaches text-first readers", "Low-production effort"],
    related: ["twitter-x-book-promotion", "social-media-strategy", "reader-engagement-content"],
  },
  {
    slug: "book-quotes-content",
    name: "Book Quotes Content",
    categoryId: "content",
    summary: "Shareable quote content that lets your book's writing speak for itself.",
    problem: "Readers share writing that moves them — but only if it's packaged to be shareable.",
    whatWeDo: "We create shareable quote content that lets your book's own writing attract readers.",
    process: ["Select quotable passages", "Design shareable formats", "Distribute across platforms", "Track engagement"],
    deliverables: ["Quote selection", "Visual formats", "Distribution plan"],
    bestFor: "Authors whose prose or ideas lend themselves to quotable moments.",
    benefits: ["Lets the writing sell the book", "Highly shareable", "Low production cost"],
    related: ["book-imagery-content", "comparative-book-content", "content-repurposing"],
  },
  {
    slug: "book-imagery-content",
    name: "Book Imagery Content",
    categoryId: "content",
    summary: "Visual content — covers, mood, aesthetics — that builds reader desire.",
    problem: "Books are visual products; flat or inconsistent imagery undersells them.",
    whatWeDo: "We create consistent visual imagery — covers, mood, aesthetics — that builds desire and recognition.",
    process: ["Define visual identity", "Plan imagery formats", "Produce consistent visuals", "Distribute and refine"],
    deliverables: ["Visual identity guide", "Imagery templates", "Distribution plan"],
    bestFor: "Authors whose genre rewards strong visual branding.",
    benefits: ["Builds visual recognition", "Reinforces brand", "Highly shareable"],
    related: ["book-quotes-content", "instagram-book-promotion", "comparative-book-content"],
  },
  {
    slug: "comparative-book-content",
    name: "Comparative Book Content",
    categoryId: "content",
    summary: "Content that places your book alongside the titles your readers already love.",
    problem: "Readers find books by comparison; content that ignores comparables misses the discovery cue.",
    whatWeDo: "We create content that honestly positions your book alongside the comparable titles your readers already love.",
    process: ["Identify comparable titles", "Plan comparison content", "Publish honestly", "Engage readers"],
    deliverables: ["Comparable-title map", "Comparison content plan", "Distribution notes"],
    bestFor: "Authors whose readers discover through 'if you liked…' reasoning.",
    benefits: ["Meets readers' discovery logic", "Builds genre fit", "Shareable"],
    related: ["book-quotes-content", "book-imagery-content", "content-repurposing"],
  },
  {
    slug: "reader-engagement-content",
    name: "Reader Engagement Content",
    categoryId: "content",
    summary: "Content designed to start and sustain conversations with your readers.",
    problem: "Most author content broadcasts; little of it invites readers to respond.",
    whatWeDo: "We create content designed to start and sustain genuine conversations with your readers.",
    process: ["Identify conversation triggers", "Plan engagement formats", "Publish and respond", "Nurture the community"],
    deliverables: ["Engagement content plan", "Conversation triggers", "Community nurture approach"],
    bestFor: "Authors building a responsive reader community.",
    benefits: ["Builds real community", "Encourages repeat engagement", "Supports future releases"],
    related: ["reader-community-development", "tiktok-book-promotion", "content-repurposing"],
  },
  {
    slug: "content-repurposing",
    name: "Content Repurposing",
    categoryId: "content",
    summary: "Turn one piece of content into platform-native versions across channels.",
    problem: "Creating fresh content for every platform is unsustainable and inconsistent.",
    whatWeDo: "We build a repurposing system that turns each core idea into platform-native versions across your channels.",
    process: ["Define core content ideas", "Map platform-native versions", "Produce efficiently", "Distribute and track"],
    deliverables: ["Repurposing framework", "Platform-native templates", "Distribution plan"],
    bestFor: "Authors who need consistent output across platforms without burnout.",
    benefits: ["More output, less effort", "Consistent messaging", "Sustainable cadence"],
    related: ["content-strategy", "social-media-strategy", "book-quotes-content"],
  },

  // ============ 05 — Author Brand & Email Audience ============
  {
    slug: "author-positioning",
    name: "Author Positioning",
    categoryId: "author-brand",
    summary: "Clarify what you are known for and who you are for.",
    problem: "Authors who try to be for everyone end up being for no one.",
    whatWeDo: "We clarify what you are known for, who you are for, and how you differ from comparable authors.",
    process: ["Analyse your work and readers", "Define your position", "Articulate the difference", "Document it"],
    deliverables: ["Positioning statement", "Audience definition", "Differentiation summary"],
    bestFor: "Authors whose identity is unclear to readers and partners.",
    benefits: ["Clarifies your identity", "Guides all messaging", "Strengthens discovery"],
    related: ["author-brand-development", "messaging", "content-pillars"],
  },
  {
    slug: "author-brand-development",
    name: "Author Brand Development",
    categoryId: "author-brand",
    summary: "Visual and verbal identity that reads as professional to readers and partners.",
    problem: "An inconsistent brand reads as amateurish to readers, reviewers, and partners.",
    whatWeDo: "We develop a coherent visual and verbal identity that reads as professional across every touchpoint.",
    process: ["Audit current brand", "Define visual and verbal identity", "Apply across touchpoints", "Document guidelines"],
    deliverables: ["Brand identity guide", "Visual and verbal direction", "Application notes"],
    bestFor: "Authors building a long-term career, not a single launch.",
    benefits: ["Builds professional credibility", "Creates consistency", "Supports future books"],
    related: ["author-positioning", "messaging", "content-pillars", "social-brand-strategy"],
  },
  {
    slug: "messaging",
    name: "Messaging",
    categoryId: "author-brand",
    summary: "Consistent language across your bio, site, listings, and pitches.",
    problem: "Different language on each platform confuses readers and weakens recognition.",
    whatWeDo: "We create consistent messaging across your bio, site, listings, and pitches.",
    process: ["Audit current messaging", "Define core messages", "Adapt per touchpoint", "Document the voice"],
    deliverables: ["Messaging framework", "Touchpoint copy", "Voice guide"],
    bestFor: "Authors with inconsistent language across channels.",
    benefits: ["Builds recognition", "Strengthens positioning", "Saves time"],
    related: ["author-positioning", "author-brand-development", "content-pillars"],
  },
  {
    slug: "content-pillars",
    name: "Content Pillars",
    categoryId: "author-brand",
    summary: "Three to five themes that make your presence recognisable.",
    problem: "Without defined themes, content drifts and your presence feels random.",
    whatWeDo: "We define three to five content pillars that make your presence recognisable and sustainable.",
    process: ["Derive pillars from positioning", "Define each pillar", "Map to formats", "Document"],
    deliverables: ["Content pillar set", "Format mapping", "Guidance"],
    bestFor: "Authors who need a repeatable content foundation.",
    benefits: ["Builds recognition", "Guides content", "Sustainable"],
    related: ["content-strategy", "social-media-strategy", "messaging"],
  },
  {
    slug: "social-brand-strategy",
    name: "Social Brand Strategy",
    categoryId: "author-brand",
    summary: "How your brand shows up, post by post, without burning you out.",
    problem: "A brand that exists on paper but not in your social posts never reaches readers.",
    whatWeDo: "We translate your brand into how it shows up, post by post, in a rhythm you can sustain.",
    process: ["Map brand to social behaviours", "Set a sustainable rhythm", "Define post archetypes", "Document"],
    deliverables: ["Social brand guide", "Post archetypes", "Rhythm plan"],
    bestFor: "Authors whose brand and social presence are disconnected.",
    benefits: ["Brand shows up consistently", "Sustainable cadence", "Recognisable presence"],
    related: ["social-media-strategy", "author-brand-development", "content-pillars"],
  },
  {
    slug: "email-newsletter-setup",
    name: "Author Newsletter Setup",
    categoryId: "author-brand",
    summary: "Reader list infrastructure, welcome sequences, and sending rhythm.",
    problem: "An email list is the most durable audience asset, but most authors never set it up properly.",
    whatWeDo: "We set up your reader list infrastructure, welcome sequence, and a sending rhythm you can maintain.",
    process: ["Choose and configure a platform", "Set up forms and segments", "Build a welcome sequence", "Define sending rhythm"],
    deliverables: ["Configured email platform", "Welcome sequence", "Sending plan"],
    bestFor: "Authors with no list, or a list that's never used.",
    benefits: ["Owns the audience", "Reachable for every release", "No algorithm dependence"],
    related: ["email-list-building", "email-opt-in-form-setup", "welcome-email-sequence", "lead-magnet-strategy"],
  },
  {
    slug: "email-list-building",
    name: "Email List Building",
    categoryId: "author-brand",
    summary: "Strategies to grow your reader list with the right subscribers.",
    problem: "A list grows slowly without a deliberate acquisition plan, or grows with the wrong readers.",
    whatWeDo: "We build list-growth strategies that attract subscribers who actually match your readership.",
    process: ["Define acquisition channels", "Plan lead magnets and funnels", "Optimise conversion", "Refine over time"],
    deliverables: ["Acquisition plan", "Funnel design", "Conversion guidance"],
    bestFor: "Authors whose list has stalled or attracts the wrong readers.",
    benefits: ["Grows a qualified list", "Improves release reach", "Compounds over time"],
    related: ["email-newsletter-setup", "email-opt-in-form-setup", "lead-magnet-strategy", "welcome-email-sequence"],
  },
  {
    slug: "email-opt-in-form-setup",
    name: "Email Opt-In Form Setup",
    categoryId: "author-brand",
    summary: "Opt-in forms placed where readers actually subscribe.",
    problem: "Most opt-in forms are hidden or unconvincing, so traffic never becomes subscribers.",
    whatWeDo: "We design and place opt-in forms where readers actually subscribe, with copy that converts.",
    process: ["Audit current forms", "Design high-conversion forms", "Place at key touchpoints", "Test and refine"],
    deliverables: ["Form designs", "Placement plan", "Copy and guidance"],
    bestFor: "Authors with traffic but few subscribers.",
    benefits: ["Converts traffic to subscribers", "Reduces friction", "Improves list quality"],
    related: ["email-newsletter-setup", "email-list-building", "lead-magnet-strategy", "welcome-email-sequence"],
  },
  {
    slug: "welcome-email-sequence",
    name: "Welcome Email Sequence",
    categoryId: "author-brand",
    summary: "An automated sequence that turns new subscribers into engaged readers.",
    problem: "New subscribers who get nothing lose interest immediately; a silent list dies.",
    whatWeDo: "We build an automated welcome sequence that introduces your work and turns new subscribers into engaged readers.",
    process: ["Map the subscriber journey", "Write the sequence", "Set automation", "Refine with data"],
    deliverables: ["Welcome sequence copy", "Automation setup", "Performance guidance"],
    bestFor: "Authors whose new subscribers go cold quickly.",
    benefits: ["Engages new subscribers", "Builds reader relationship", "Sets up future releases"],
    related: ["email-newsletter-setup", "email-engagement-campaigns", "email-list-building"],
  },
  {
    slug: "email-engagement-campaigns",
    name: "Email Engagement Campaigns",
    categoryId: "author-brand",
    summary: "Campaigns that keep your list warm and responsive between releases.",
    problem: "A list you only email at launch goes cold and stops opening.",
    whatWeDo: "We run engagement campaigns that keep your list warm and responsive between releases.",
    process: ["Plan engagement content", "Segment the list", "Send on a rhythm", "Track and refine"],
    deliverables: ["Engagement campaign plan", "Segmentation strategy", "Content calendar"],
    bestFor: "Authors whose list only hears from them at launch.",
    benefits: ["Keeps the list responsive", "Improves launch reach", "Builds reader loyalty"],
    related: ["welcome-email-sequence", "email-list-building", "email-newsletter-setup"],
  },
  {
    slug: "lead-magnet-strategy",
    name: "Reader Freebie / Lead Magnet Strategy",
    categoryId: "author-brand",
    summary: "Reader magnets that attract the right subscribers, not just any subscribers.",
    problem: "Generic magnets attract freebie-seekers who never read your books.",
    whatWeDo: "We design reader magnets that attract subscribers who genuinely match your readership.",
    process: ["Define the right magnet", "Create or guide the asset", "Build the funnel", "Refine conversion"],
    deliverables: ["Magnet concept", "Funnel design", "Conversion guidance"],
    bestFor: "Authors whose lead magnet attracts the wrong audience.",
    benefits: ["Attracts qualified readers", "Improves list quality", "Supports future releases"],
    related: ["email-list-building", "email-opt-in-form-setup", "email-newsletter-setup"],
  },
  {
    slug: "reader-community-development",
    name: "Reader Community Development",
    categoryId: "author-brand",
    summary: "Turn readers into a community that returns for the next release.",
    problem: "One-off readers don't return; communities do.",
    whatWeDo: "We help turn readers into a community that returns for your next release.",
    process: ["Define the community space", "Plan engagement rituals", "Nurture members", "Refine"],
    deliverables: ["Community plan", "Engagement rituals", "Nurture approach"],
    bestFor: "Authors building a durable reader base across multiple books.",
    benefits: ["Builds loyalty", "Improves release reach", "Creates word-of-mouth"],
    related: ["reader-engagement-content", "email-engagement-campaigns", "book-club-outreach"],
  },

  // ============ 06 — Media & Podcast Outreach ============
  {
    slug: "podcast-outreach",
    name: "Podcast Outreach",
    categoryId: "media",
    summary: "Pitch you to shows whose audiences overlap with your ideal reader.",
    problem: "The right podcast appearance can move books, but generic mass pitches get ignored.",
    whatWeDo: "We research shows whose audiences overlap with your ideal reader and pitch you with genuine relevance.",
    process: ["Research relevant shows", "Qualify audience fit", "Craft a tailored pitch", "Track bookings"],
    deliverables: ["Qualified podcast list", "Tailored pitch copy", "Booking tracker"],
    bestFor: "Authors whose readers listen to genre or topic podcasts.",
    benefits: ["Reaches engaged audiences", "Builds authority", "Creates shareable content"],
    related: ["book-interview-outreach", "youtube-channel-outreach", "book-blogger-outreach"],
  },
  {
    slug: "youtube-channel-outreach",
    name: "YouTube Channel Outreach",
    categoryId: "media",
    summary: "Outreach to BookTube and topic channels whose viewers match your readers.",
    problem: "BookTube and topic channels have loyal audiences, but only respond to relevant, considered pitches.",
    whatWeDo: "We identify YouTube channels whose viewers match your readers and pitch for honest coverage or features.",
    process: ["Research relevant channels", "Qualify audience fit", "Craft tailored pitches", "Track responses"],
    deliverables: ["Qualified channel list", "Pitch copy", "Response tracker"],
    bestFor: "Authors whose readers watch book or topic YouTube channels.",
    benefits: ["Reaches video audiences", "Creates lasting content", "Builds authority"],
    related: ["podcast-outreach", "book-interview-outreach", "bookstagram-outreach"],
  },
  {
    slug: "book-interview-outreach",
    name: "Book Interview Outreach",
    categoryId: "media",
    summary: "Outreach to interview shows, columns, and features that reach your readers.",
    problem: "Interviews build authority, but only when pitched to the right outlets with the right angle.",
    whatWeDo: "We pitch you for interviews, columns, and features with an angle that fits each outlet's audience.",
    process: ["Define your interview angles", "Research relevant outlets", "Tailor each pitch", "Track bookings"],
    deliverables: ["Angle and outlet list", "Tailored pitches", "Booking tracker"],
    bestFor: "Authors building authority through interviews and features.",
    benefits: ["Builds authority", "Reaches new audiences", "Creates shareable coverage"],
    related: ["podcast-outreach", "youtube-channel-outreach", "non-fiction-reviewer-outreach"],
  },

  // ============ 07 — Bookstores, Libraries & Institutional Sales ============
  {
    slug: "book-club-outreach",
    name: "Book Club Outreach",
    categoryId: "institutional",
    summary: "Place discussion-friendly titles in front of active reading groups.",
    problem: "Book clubs drive sustained word-of-mouth, but only when matched to discussion-friendly titles.",
    whatWeDo: "We identify active reading groups whose taste matches your book and place it for genuine discussion.",
    process: ["Research relevant book clubs", "Assess fit and discussion potential", "Provide discussion materials", "Track engagement"],
    deliverables: ["Book club list", "Discussion guide", "Engagement notes"],
    bestFor: "Authors of discussion-friendly fiction or non-fiction.",
    benefits: ["Drives word-of-mouth", "Builds reader loyalty", "Sustained discovery"],
    related: ["reader-community-development", "reader-outreach", "library-outreach"],
  },
  {
    slug: "bulk-buyer-outreach",
    name: "Bulk Buyer Outreach",
    categoryId: "institutional",
    summary: "Outreach to organisations and retailers who buy in quantity.",
    problem: "Some books sell in bulk to organisations or retailers, but only through deliberate outreach.",
    whatWeDo: "We identify organisations and retailers who may buy in quantity and approach them with relevant proposals.",
    process: ["Identify bulk-buyer prospects", "Tailor proposals", "Manage outreach", "Track responses"],
    deliverables: ["Prospect list", "Proposal copy", "Response tracker"],
    bestFor: "Non-fiction and gift-friendly titles with institutional appeal.",
    benefits: ["Opens volume sales", "Diversifies revenue", "Builds relationships"],
    related: ["institutional-book-sales", "independent-bookstore-outreach", "library-outreach"],
  },
  {
    slug: "bookstagram-outreach",
    name: "Bookstagram Outreach",
    categoryId: "institutional",
    summary: "Outreach to Bookstagram accounts whose followers match your readers.",
    problem: "Bookstagram influencers move books, but only when the match and approach are genuine.",
    whatWeDo: "We identify Bookstagram accounts whose followers match your readers and approach them for honest coverage.",
    process: ["Research relevant accounts", "Qualify audience fit", "Approach genuinely", "Track coverage"],
    deliverables: ["Account list", "Outreach copy", "Coverage tracker"],
    bestFor: "Authors whose readers discover books through Bookstagram.",
    benefits: ["Reaches visual reader communities", "Builds honest coverage", "Highly shareable"],
    related: ["instagram-book-promotion", "book-blogger-outreach", "book-imagery-content"],
  },
  {
    slug: "subscription-box-outreach",
    name: "Subscription Box Outreach",
    categoryId: "institutional",
    summary: "Outreach to subscription boxes whose themes fit your book.",
    problem: "Subscription boxes offer sustained visibility, but only when the thematic fit is right.",
    whatWeDo: "We research subscription boxes whose themes fit your book and pitch for inclusion.",
    process: ["Research relevant boxes", "Assess thematic fit", "Tailor pitches", "Track responses"],
    deliverables: ["Box prospect list", "Pitch copy", "Response tracker"],
    bestFor: "Authors whose book fits a recognisable niche or theme.",
    benefits: ["Sustained visibility", "Reaches engaged subscribers", "Builds niche presence"],
    related: ["bookstagram-outreach", "bulk-buyer-outreach", "institutional-book-sales"],
  },
  {
    slug: "library-outreach",
    name: "Library Outreach",
    categoryId: "institutional",
    summary: "Outreach to public and academic libraries to place your book with readers.",
    problem: "Libraries are a major discovery channel that most authors never approach.",
    whatWeDo: "We run outreach to public and academic libraries to place your book with librarian-curated readers.",
    process: ["Identify relevant library systems", "Prepare library-ready materials", "Approach librarians", "Track placements"],
    deliverables: ["Library prospect list", "Librarian materials", "Placement tracker"],
    bestFor: "Authors whose book suits library collections and reader discovery.",
    benefits: ["Reaches librarian-curated readers", "Sustained presence", "Builds credibility"],
    related: ["institutional-book-sales", "university-department-outreach", "book-club-outreach"],
  },
  {
    slug: "independent-bookstore-outreach",
    name: "Independent Bookstore Outreach",
    categoryId: "institutional",
    summary: "Outreach to independent bookstores for placement and handselling.",
    problem: "Independent bookstores handsell books they believe in — but only if approached well.",
    whatWeDo: "We approach independent bookstores with a relevant case for placement and handselling.",
    process: ["Identify relevant stores", "Prepare bookseller materials", "Approach genuinely", "Track relationships"],
    deliverables: ["Store prospect list", "Bookseller materials", "Relationship tracker"],
    bestFor: "Authors whose book suits independent bookstore curation.",
    benefits: ["Builds handselling relationships", "Sustained discovery", "Local credibility"],
    related: ["library-outreach", "bulk-buyer-outreach", "book-club-outreach"],
  },
  {
    slug: "university-department-outreach",
    name: "University Department Outreach",
    categoryId: "institutional",
    summary: "Outreach to university departments for course adoption and reading lists.",
    problem: "Academic and serious non-fiction often finds its audience through departments, not ads.",
    whatWeDo: "We approach university departments whose curricula or reading lists fit your book.",
    process: ["Identify relevant departments", "Prepare academic materials", "Approach faculty", "Track responses"],
    deliverables: ["Department prospect list", "Academic materials", "Response tracker"],
    bestFor: "Academic and serious non-fiction authors.",
    benefits: ["Builds academic authority", "Sustained adoption", "Reaches student readers"],
    related: ["library-outreach", "institutional-book-sales", "philosophy-blogger-outreach", "psychology-blogger-outreach"],
  },
  {
    slug: "institutional-book-sales",
    name: "Institutional Book Sales",
    categoryId: "institutional",
    summary: "Coordinated outreach to institutions that purchase books at scale.",
    problem: "Institutional sales channels are real but require deliberate, relationship-based outreach.",
    whatWeDo: "We coordinate outreach to institutions — libraries, departments, organisations — that purchase books at scale.",
    process: ["Map institutional buyers", "Tailor proposals", "Manage relationships", "Track sales"],
    deliverables: ["Buyer map", "Proposal materials", "Sales tracker"],
    bestFor: "Authors whose book suits institutional or bulk purchase.",
    benefits: ["Diversifies sales channels", "Builds lasting relationships", "Sustained revenue"],
    related: ["bulk-buyer-outreach", "library-outreach", "university-department-outreach"],
  },

  // ============ 08 — Pre-Launch & Book Launch ============
  {
    slug: "pre-launch-campaigns",
    name: "Pre-Launch Campaigns",
    categoryId: "launch",
    summary: "Audience warm-up, positioning, and asset preparation in the months before release.",
    problem: "Launches are decided before launch day; without pre-launch work there is nothing to amplify.",
    whatWeDo: "We run the audience warm-up, positioning, and asset preparation that makes launch week effective.",
    process: ["Set the pre-launch timeline", "Build audience and assets", "Recruit advance readers", "Sequence content and outreach"],
    deliverables: ["Pre-launch plan", "Asset checklist", "Advance-reader plan"],
    bestFor: "Authors with a release 60+ days away.",
    benefits: ["Builds launch momentum", "Recruits early readers", "Reduces launch-week chaos"],
    related: ["arc-strategy", "pre-order-strategy", "launch-week-strategy", "email-engagement-campaigns"],
  },
  {
    slug: "bulk-pre-orders",
    name: "Bulk Pre-Orders",
    categoryId: "launch",
    summary: "Strategies to build pre-order volume before release day.",
    problem: "Pre-order momentum signals demand to retailers, but most authors never build it deliberately.",
    whatWeDo: "We build strategies that generate pre-order volume from your audience and partners before release.",
    process: ["Map pre-order sources", "Plan incentives and outreach", "Execute before release", "Track volume"],
    deliverables: ["Pre-order plan", "Outreach and incentives", "Volume tracker"],
    bestFor: "Authors whose launch benefits from pre-order momentum.",
    benefits: ["Signals demand", "Builds launch momentum", "Improves launch-day rank"],
    related: ["pre-order-strategy", "pre-launch-campaigns", "launch-week-strategy"],
  },
  {
    slug: "pre-order-strategy",
    name: "Pre-Order Strategy",
    categoryId: "launch",
    summary: "A deliberate plan for how pre-orders support your launch goals.",
    problem: "Pre-orders without strategy miss their chance to build rank and signal demand.",
    whatWeDo: "We design a pre-order strategy that aligns pricing, timing, and outreach with your launch goals.",
    process: ["Define launch goals", "Set pre-order pricing and timing", "Plan outreach", "Execute and track"],
    deliverables: ["Pre-order strategy", "Pricing and timing plan", "Outreach plan"],
    bestFor: "Authors planning a release who want pre-orders to support rank.",
    benefits: ["Builds demand signal", "Improves launch rank", "Aligns with goals"],
    related: ["bulk-pre-orders", "pricing-strategy", "pre-launch-campaigns"],
  },
  {
    slug: "launch-week-strategy",
    name: "Launch Week Momentum Campaign",
    categoryId: "launch",
    summary: "A day-by-day plan so nothing depends on improvisation.",
    problem: "Launch week chaos means missed opportunities and wasted momentum.",
    whatWeDo: "We build a day-by-day launch-week plan so every channel fires in sequence, not by improvisation.",
    process: ["Map launch-week channels", "Sequence day-by-day actions", "Coordinate outreach and ads", "Execute and adjust"],
    deliverables: ["Launch-week plan", "Channel sequence", "Daily action checklist"],
    bestFor: "Authors approaching launch week.",
    benefits: ["Maximises launch momentum", "Reduces chaos", "Coordinates every channel"],
    related: ["launch-campaigns", "pre-launch-campaigns", "post-launch-promotion"],
  },
  {
    slug: "launch-campaigns",
    name: "Launch Campaigns",
    categoryId: "launch",
    summary: "Coordinated promotion across email, social, outreach, and advertising.",
    problem: "A launch is only as strong as the coordination across its channels.",
    whatWeDo: "We coordinate a launch campaign across email, social, outreach, and advertising into one effort.",
    process: ["Define launch objectives", "Coordinate channels", "Execute across the week", "Report outcomes"],
    deliverables: ["Launch campaign plan", "Channel coordination", "Outcome report"],
    bestFor: "Authors launching a new release.",
    benefits: ["Unified launch effort", "Maximises reach", "Clear reporting"],
    related: ["launch-week-strategy", "pre-launch-campaigns", "amazon-ads"],
  },
  {
    slug: "post-launch-promotion",
    name: "Post-Launch Follow-Up",
    categoryId: "launch",
    summary: "Sustain discoverability once launch-week attention fades.",
    problem: "Most authors abandon promotion after launch week, losing all the momentum they built.",
    whatWeDo: "We sustain discoverability after launch with follow-up outreach, content, and optimisation.",
    process: ["Review launch results", "Plan follow-up activity", "Sustain outreach and content", "Optimise"],
    deliverables: ["Post-launch plan", "Follow-up campaign", "Performance review"],
    bestFor: "Authors whose launch attention has faded.",
    benefits: ["Sustains momentum", "Improves long-tail discovery", "Protects launch investment"],
    related: ["launch-campaigns", "launch-week-strategy", "optimization"],
  },
  {
    slug: "pricing-strategy",
    name: "Pricing Strategy",
    categoryId: "launch",
    summary: "Pricing decisions that support your launch and long-tail goals.",
    problem: "Pricing by guesswork leaves money on the table or prices readers out.",
    whatWeDo: "We define pricing decisions — launch price, transitions, and tiers — that support your goals.",
    process: ["Analyse genre pricing", "Define launch and transition pricing", "Plan promotions", "Track results"],
    deliverables: ["Pricing strategy", "Transition plan", "Promotion calendar"],
    bestFor: "Authors unsure how to price a launch or backlist.",
    benefits: ["Supports launch rank", "Protects revenue", "Data-informed"],
    related: ["pre-order-strategy", "pre-launch-campaigns", "marketing-strategy-audit"],
  },

  // ============ 09 — Marketing Strategy & Campaign Management ============
  {
    slug: "marketing-strategy-audit",
    name: "Marketing Strategy Audit",
    categoryId: "strategy",
    summary: "A full review of what your book needs and what has already been tried.",
    problem: "Before tactics, you need to know what's actually working and what isn't.",
    whatWeDo: "We audit your book's positioning, listing, audience, and past efforts to define what it needs first.",
    process: ["Review positioning and listing", "Assess audience and channels", "Evaluate past efforts", "Prioritise next steps"],
    deliverables: ["Audit report", "Prioritised recommendations", "Action plan"],
    bestFor: "Authors unsure what their book actually needs.",
    benefits: ["Clarifies priorities", "Avoids wasted spend", "Grounds the strategy"],
    related: ["promotional-strategy-review", "30-60-day-marketing-campaign", "amazon-book-description-optimization"],
  },
  {
    slug: "promotional-strategy-review",
    name: "Promotional Strategy Review",
    categoryId: "strategy",
    summary: "An honest review of your current or planned promotional strategy.",
    problem: "Many authors are mid-campaign, unsure whether to continue, change, or stop.",
    whatWeDo: "We review your current or planned promotional strategy and tell you honestly what to keep, change, or stop.",
    process: ["Review the current plan", "Assess what's working", "Identify gaps and risks", "Recommend changes"],
    deliverables: ["Strategy review", "Keep/change/stop guidance", "Refinement plan"],
    bestFor: "Authors already promoting who need an honest outside view.",
    benefits: ["Honest outside perspective", "Reduces wasted spend", "Refines the plan"],
    related: ["marketing-strategy-audit", "30-60-day-marketing-campaign", "campaign-strategy"],
  },
  {
    slug: "30-60-day-marketing-campaign",
    name: "30–60 Day Marketing Campaign",
    categoryId: "strategy",
    summary: "A defined, time-boxed campaign with clear success measures.",
    problem: "Open-ended promotion drifts; defined campaigns produce measurable outcomes.",
    whatWeDo: "We run a defined 30–60 day campaign with clear objectives, channels, and success measures.",
    process: ["Set campaign objectives", "Choose and sequence channels", "Execute on schedule", "Report against measures"],
    deliverables: ["Campaign plan", "Execution calendar", "Outcome report"],
    bestFor: "Authors who need focused, measurable effort over a set period.",
    benefits: ["Measurable outcomes", "Focused effort", "Clear reporting"],
    related: ["marketing-strategy-audit", "campaign-strategy", "launch-campaigns"],
  },
];

// Strategic bundling pathways shown on the Services page.
export const SERVICE_PATHWAYS: {
  label: string;
  title: string;
  body: string;
  steps: { name: string; slug: string }[];
}[] = [
  {
    label: "Discover",
    title: "Make the book findable",
    body: "Research first, then align the listing with how readers actually search and browse.",
    steps: [
      { name: "Marketing Strategy Audit", slug: "marketing-strategy-audit" },
      { name: "Amazon Category Research", slug: "amazon-category-research" },
      { name: "Amazon Keyword Optimization", slug: "amazon-keyword-optimization" },
      { name: "Backend Metadata Optimization", slug: "backend-metadata-optimization" },
      { name: "Amazon Book Description Optimization", slug: "amazon-book-description-optimization" },
    ],
  },
  {
    label: "Build",
    title: "Build the presence",
    body: "Content, social, and email that make the author recognisable between books.",
    steps: [
      { name: "Content Strategy", slug: "content-strategy" },
      { name: "Social Media Strategy", slug: "social-media-strategy" },
      { name: "Author Newsletter Setup", slug: "email-newsletter-setup" },
      { name: "Reader Engagement Content", slug: "reader-engagement-content" },
    ],
  },
  {
    label: "Reach",
    title: "Reach the right readers",
    body: "Honest outreach to reviewers, bloggers, podcasts, and communities that match your book.",
    steps: [
      { name: "Book Reviewer Outreach", slug: "book-reviewer-outreach" },
      { name: "Book Blogger Outreach", slug: "book-blogger-outreach" },
      { name: "Podcast Outreach", slug: "podcast-outreach" },
      { name: "Bookstagram Outreach", slug: "bookstagram-outreach" },
      { name: "Book Club Outreach", slug: "book-club-outreach" },
    ],
  },
  {
    label: "Launch",
    title: "Launch with momentum",
    body: "Pre-launch, advance readers, pre-orders, launch week, and follow-up in one sequence.",
    steps: [
      { name: "Pre-Launch Campaigns", slug: "pre-launch-campaigns" },
      { name: "Advance Review (ARC) Strategy", slug: "arc-strategy" },
      { name: "Bulk Pre-Orders", slug: "bulk-pre-orders" },
      { name: "Launch Week Momentum Campaign", slug: "launch-week-strategy" },
      { name: "Post-Launch Follow-Up", slug: "post-launch-promotion" },
    ],
  },
  {
    label: "Grow",
    title: "Grow the career",
    body: "Ads, audience, email, and content that compound across every release.",
    steps: [
      { name: "Amazon Ads", slug: "amazon-ads" },
      { name: "Email List Building", slug: "email-list-building" },
      { name: "Email Engagement Campaigns", slug: "email-engagement-campaigns" },
      { name: "Content Repurposing", slug: "content-repurposing" },
      { name: "Marketing Strategy Audit", slug: "marketing-strategy-audit" },
    ],
  },
];

export function getService(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug);
}

export function getCategory(id: string): ServiceCategory | undefined {
  return SERVICE_CATEGORIES.find((c) => c.id === id);
}

export function servicesByCategory(categoryId: string): Service[] {
  return SERVICES.filter((s) => s.categoryId === categoryId);
}

export function relatedServices(slugs: string[]): Service[] {
  return slugs.map((slug) => getService(slug)).filter((s): s is Service => Boolean(s));
}
