/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmazonOptimizationRouteImport } from './routes/amazon-optimization'
import { Route as AuthorBrandRouteImport } from './routes/author-brand'
import { Route as AuthorWebsiteRouteImport } from './routes/author-website'
import { Route as BookAuditRouteImport } from './routes/book-audit'
import { Route as BookLaunchRouteImport } from './routes/book-launch'
import { Route as BookMarketingRouteImport } from './routes/book-marketing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GoodreadsMarketingRouteImport } from './routes/goodreads-marketing'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkWithUsRouteImport } from './routes/work-with-us'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonOptimizationRoute = AmazonOptimizationRouteImport.update({
  id: '/amazon-optimization',
  path: '/amazon-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorBrandRoute = AuthorBrandRouteImport.update({
  id: '/author-brand',
  path: '/author-brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorWebsiteRoute = AuthorWebsiteRouteImport.update({
  id: '/author-website',
  path: '/author-website',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAuditRoute = BookAuditRouteImport.update({
  id: '/book-audit',
  path: '/book-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookLaunchRoute = BookLaunchRouteImport.update({
  id: '/book-launch',
  path: '/book-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMarketingRoute = BookMarketingRouteImport.update({
  id: '/book-marketing',
  path: '/book-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodreadsMarketingRoute = GoodreadsMarketingRouteImport.update({
  id: '/goodreads-marketing',
  path: '/goodreads-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWithUsRoute = WorkWithUsRouteImport.update({
  id: '/work-with-us',
  path: '/work-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amazon-optimization': typeof AmazonOptimizationRoute
  '/author-brand': typeof AuthorBrandRoute
  '/author-website': typeof AuthorWebsiteRoute
  '/book-audit': typeof BookAuditRoute
  '/book-launch': typeof BookLaunchRoute
  '/book-marketing': typeof BookMarketingRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/goodreads-marketing': typeof GoodreadsMarketingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amazon-optimization': typeof AmazonOptimizationRoute
  '/author-brand': typeof AuthorBrandRoute
  '/author-website': typeof AuthorWebsiteRoute
  '/book-audit': typeof BookAuditRoute
  '/book-launch': typeof BookLaunchRoute
  '/book-marketing': typeof BookMarketingRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/goodreads-marketing': typeof GoodreadsMarketingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amazon-optimization': typeof AmazonOptimizationRoute
  '/author-brand': typeof AuthorBrandRoute
  '/author-website': typeof AuthorWebsiteRoute
  '/book-audit': typeof BookAuditRoute
  '/book-launch': typeof BookLaunchRoute
  '/book-marketing': typeof BookMarketingRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/goodreads-marketing': typeof GoodreadsMarketingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amazon-optimization'
    | '/author-brand'
    | '/author-website'
    | '/book-audit'
    | '/book-launch'
    | '/book-marketing'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/goodreads-marketing'
    | '/pricing'
    | '/privacy-policy'
    | '/resources'
    | '/terms'
    | '/work-with-us'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amazon-optimization'
    | '/author-brand'
    | '/author-website'
    | '/book-audit'
    | '/book-launch'
    | '/book-marketing'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/goodreads-marketing'
    | '/pricing'
    | '/privacy-policy'
    | '/resources'
    | '/terms'
    | '/work-with-us'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amazon-optimization'
    | '/author-brand'
    | '/author-website'
    | '/book-audit'
    | '/book-launch'
    | '/book-marketing'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/goodreads-marketing'
    | '/pricing'
    | '/privacy-policy'
    | '/resources'
    | '/terms'
    | '/work-with-us'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmazonOptimizationRoute: typeof AmazonOptimizationRoute
  AuthorBrandRoute: typeof AuthorBrandRoute
  AuthorWebsiteRoute: typeof AuthorWebsiteRoute
  BookAuditRoute: typeof BookAuditRoute
  BookLaunchRoute: typeof BookLaunchRoute
  BookMarketingRoute: typeof BookMarketingRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  GoodreadsMarketingRoute: typeof GoodreadsMarketingRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  WorkWithUsRoute: typeof WorkWithUsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon-optimization': {
      id: '/amazon-optimization'
      path: '/amazon-optimization'
      fullPath: '/amazon-optimization'
      preLoaderRoute: typeof AmazonOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-brand': {
      id: '/author-brand'
      path: '/author-brand'
      fullPath: '/author-brand'
      preLoaderRoute: typeof AuthorBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-website': {
      id: '/author-website'
      path: '/author-website'
      fullPath: '/author-website'
      preLoaderRoute: typeof AuthorWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-audit': {
      id: '/book-audit'
      path: '/book-audit'
      fullPath: '/book-audit'
      preLoaderRoute: typeof BookAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-launch': {
      id: '/book-launch'
      path: '/book-launch'
      fullPath: '/book-launch'
      preLoaderRoute: typeof BookLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-marketing': {
      id: '/book-marketing'
      path: '/book-marketing'
      fullPath: '/book-marketing'
      preLoaderRoute: typeof BookMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodreads-marketing': {
      id: '/goodreads-marketing'
      path: '/goodreads-marketing'
      fullPath: '/goodreads-marketing'
      preLoaderRoute: typeof GoodreadsMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-with-us': {
      id: '/work-with-us'
      path: '/work-with-us'
      fullPath: '/work-with-us'
      preLoaderRoute: typeof WorkWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmazonOptimizationRoute: AmazonOptimizationRoute,
  AuthorBrandRoute: AuthorBrandRoute,
  AuthorWebsiteRoute: AuthorWebsiteRoute,
  BookAuditRoute: BookAuditRoute,
  BookLaunchRoute: BookLaunchRoute,
  BookMarketingRoute: BookMarketingRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  GoodreadsMarketingRoute: GoodreadsMarketingRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  WorkWithUsRoute: WorkWithUsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
